language: csharp
dist: xenial
mono: none
dotnet: 3.0
script:
- cd src
- dotnet build
- dotnet publish --output ../../output
- cd ../output
- dotnet test DotNetCoreKatas.Command.Adapter.UnitTests.dll DotNetCoreKatas.Query.Adapter.UnitTests.dll DotNetCoreKatas.Core.UnitTests.dll DotNetCoreKatas.Domain.UnitTests.dll