language: csharp
dist: xenial
mono: none
dotnet: 3.0
script:
- cd src
- dotnet build
- dotnet publish --output ../../output
- cd ../output
- dotnet ~/.nuget/packages/xunit.runner.console/2.4.1/tools/netcoreapp3.0/xunit.console.dll DotNetCoreKatas.Command.Adapter.UnitTests.dll DotNetCoreKatas.Query.Adapter.UnitTests.dll DotNetCoreKatas.Core.UnitTests.dll DotNetCoreKatas.Domain.UnitTests.dll