language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
before_script: cd src
script:
- dotnet restore DotNetCoreKatas.sln
- dotnet build DotNetCoreKatas.sln
- dotnet test --filter FullyQualifiedName~UnitTests