language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
before_script: cd src
script:
- dotnet restore
- dotnet build
- cd .\DotNetCoreKatas.Command.Adapter.UnitTests
- dotnet test
- cd ..
- cd .\DotNetCoreKatas.Query.Adapter.UnitTests
- dotnet test
- cd ..
- cd .\DotNetCoreKatas.Core.UnitTests
- dotnet test
- cd ..
- cd .\DotNetCoreKatas.Domain.UnitTests
- dotnet test
- cd ..
- cd .\DotNetCoreWebApi.Host.UnitTests
- dotnet test