language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
before_script:
script:
- dotnet restore src\DotNetCoreKatas.sln
- dotnet build src\DotNetCoreKatas.sln
- dotnet test src\DotNetCoreKatas.Command.Adapter.UnitTests\DotNetCoreKatas.Command.Adapter.UnitTests.csproj
- dotnet test src\DotNetCoreKatas.Query.Adapter.UnitTests\DotNetCoreKatas.Query.Adapter.UnitTests.csproj
- dotnet test src\DotNetCoreKatas.Core.UnitTests\DotNetCoreKatas.Core.UnitTests.csproj
- dotnet test src\DotNetCoreKatas.Domain.UnitTests\DotNetCoreKatas.Domain.UnitTests.csproj
- dotnet test src\DotNetCoreWebApi.Host.UnitTests\DotNetCoreWebApi.Host.UnitTests.csproj