language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
script:
- cd src
- dotnet build
- dotnet publish --output ../../output
- cd ../output
- dotnet ~/.nuget/packages/xunit.runner.console/2.4.0/tools/netcoreapp2.0/xunit.console.dll DotNetCoreKatas.Command.Adapter.UnitTests.dll DotNetCoreKatas.Query.Adapter.UnitTests.dll DotNetCoreKatas.Core.UnitTests.dll DotNetCoreKatas.Domain.UnitTests.dll